#!/usr/bin/python
# -*- coding: utf-8 -*-
f=open('21_utf8.txt','r')
for line in f:
	line=line.replace('\"','\n')
	line=line.replace('.','\n')
	line=line.replace(',','\n')
	line=line.replace('\'','\n')
	line=line.replace(')','\n')
	line=line.replace('[','\n')
	line=line.replace(']','\n')
	line=line.replace('\\','\n')
	line=line.replace('/','\n')
	line=line.replace('…','\n')
	line=line.replace('(','\n')
	line=line.replace(':','\n')
	line=line.replace(';','\n')
	line=line.replace('%','\n')
	line=line.replace('’','\n')
	line=line.replace('‘','\n')
	line=line.replace('!','\n')
	line=line.replace('“','\n')
	line=line.replace('*','\n')
	line=line.replace('?','\n')
	line=line.replace('।','\n')
	line=line.replace('-','\n')
	line=line.replace(' ','\n')
	line=line.replace('\t','\n')
	print line
